# Site settings
title: "Ilia Zlobin Online Resume"
description: "Ilia Zlobin Online Resume on GitHub Pages"

# Build settings
markdown: kramdown
kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # parse markdown inside block-level HTML tag
  parse_block_html: true
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ilia Zlobin"
resume_title:                   "Senior DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "iliazlobin91@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Minsk, Belarus, 220114"

resume_header_contact_info:     "Minsk, Belarus, 220114 • iliazlobin91@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>An experienced, certified engineer with a current focus on growing as a professional through acquiring practical knowledge, continuous learning and perfecting communication, solving industry problems effectively thought applying identified automation practices and promoting the best progressive methods, as well as mentoring and educating others to quickly achieve professional results.
</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/iliazlobin"
  resume_github_url:            "https://github.com/iliazlobin"
  resume_twitter_url:           "http://twitter.com/iliazlobin"
  resume_facebook_url:          "https://www.facebook.com/iliazlobin91"
  resume_instagram_url:         "http://instagram.com/iliazlobin91"
  resume_medium_url:            "https://medium.com/@iliazlobin"
resume_print_social_links:      true

# Design settings
resume_theme:                   cayman

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
